#!/bin/bash
#
#  This script expects to be in the top level of the ubuntu iso
#  directory and depends on the "README.diskdefines" file being present.
#  
#  Scripted process to make a new ISO after changes to the 
#  preseed file have been made. This is to speed up the 
#  testing process.
#

# If script has argument for user
USER_NAME="$1"

if ! [ -f README.diskdefines ] ; then
    echo "[ERROR]"
    echo "  $0 is not in the top directory of the Ubuntu ISO."
    echo "  Move $0 to the top directory and run again."
    exit 0
fi

# Distro
DISTRO=$(head -n 1 README.diskdefines | awk '{ print $4 }')

# Make a directory to hold the ISO
if ! [ -d $HOME/UbuntuUnattendedISO/ ] ; then
    mkdir $HOME/UbuntuUnattendedISO/
fi

# Remove the old ISO if it exists
if [ -f $HOME/UbuntuUnattendedISO/ubuntu-${DISTRO}-unattended-install.iso ] ; then
    rm $HOME/UbuntuUnattendedISO/ubuntu-${DISTRO}-unattended-install.iso
fi

# Edit the preseed file using vim
vim ./ks.preseed

# Make ISO command
mkisofs -D -r -V "UNATTENDED_UBUNTU" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $HOME/UbuntuUnattendedISO/ubuntu-${DISTRO}-unattended-install.iso .

# Not required
# Move ISO to specified user's Document directory
if ! [ -z $1 ] ; then
    rm /home/${USER_NAME}/Documents/ubuntu-${DISTRO}-unattended-install.iso
    cp $HOME/UbuntuUnattendedISO/ubuntu-${DISTRO}-unattended-install.iso /home/${USER_NAME}/Documents/
fi
